import { UserRole, UrgencyLevel, RequestStatus, Badge, User, Request } from "@/types/backend-mock";

export const MOCK_USERS: User[] = [
  {
    id: "user1",
    clerkId: "user_2p8X9vH2n7M3k4Q6j1W0L5rTzS1",
    email: "john@example.com",
    name: "John Doe",
    role: UserRole.BOTH,
    skills: ["React", "TypeScript", "Next.js"],
    interests: ["AI", "Open Source"],
    location: "New York, USA",
    bio: "Passionate developer looking to help and learn.",
    trustScore: 850,
    badges: [Badge.HELPER, Badge.TRUSTED],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "user2",
    clerkId: "user_9k5M2L1R8P3Q4N7V0X6Z9Y2S1B4",
    email: "jane@example.com",
    name: "Jane Smith",
    role: UserRole.CAN_HELP,
    skills: ["Python", "Data Science", "Machine Learning"],
    interests: ["Education", "Healthcare"],
    location: "London, UK",
    bio: "Data enthusiast with a love for teaching.",
    trustScore: 920,
    badges: [Badge.TOP_CONTRIBUTOR, Badge.COMMUNITY_LEADER],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const MOCK_REQUESTS: Request[] = [
  {
    id: "req1",
    title: "Help with React Hooks",
    description: "I'm struggling with useEffect and custom hooks. Need someone to explain how to manage complex state transitions.",
    category: "Development",
    tags: ["React", "Frontend", "Hooks"],
    urgency: UrgencyLevel.MEDIUM,
    status: RequestStatus.OPEN,
    aiSummary: "The user needs assistance with React's state management and lifecycle hooks.",
    userId: "user1",
    user: MOCK_USERS[0],
    helpOffers: [],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "req2",
    title: "Python Data Analysis Review",
    description: "Looking for someone to review my pandas data cleaning script. It's working but quite slow on large datasets.",
    category: "Data Science",
    tags: ["Python", "Pandas", "Performance"],
    urgency: UrgencyLevel.HIGH,
    status: RequestStatus.IN_PROGRESS,
    aiSummary: "User is seeking performance optimization for a data cleaning script using pandas.",
    userId: "user2",
    user: MOCK_USERS[1],
    helpOffers: [],
    helperId: "user1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
