import { UrgencyLevel, RequestStatus } from "@/types/backend-mock";
import type { Request } from "@/types/backend-mock";

export const MOCK_REQUESTS: Request[] = [
  {
    id: "req1",
    title: "Help with React Hooks",
    description: "I'm struggling with useEffect and custom hooks. Need someone to explain how to manage complex state transitions.",
    category: "Development",
    tags: ["React", "Frontend", "Hooks"],
    urgency: UrgencyLevel.MEDIUM,
    status: RequestStatus.OPEN,
    aiSummary: "The user needs assistance with React's state management and lifecycle hooks.",
    userId: "mock-user-1",
    user: {
      id: "mock-user-1",
      clerkId: "mock_clerk_1",
      email: "alice@example.com",
      name: "Alice Johnson",
      role: "BOTH" as any,
      skills: ["React", "TypeScript"],
      interests: ["Web Development"],
      trustScore: 850,
      badges: [],
      createdAt: new Date("2026-07-01"),
      updatedAt: new Date("2026-07-01"),
    },
    helpOffers: [],
    createdAt: new Date("2026-07-14"),
    updatedAt: new Date("2026-07-14"),
  },
  {
    id: "req2",
    title: "Python Data Analysis Review",
    description: "Looking for someone to review my pandas data cleaning script. It's working but quite slow on large datasets.",
    category: "Data Science",
    tags: ["Python", "Pandas", "Performance"],
    urgency: UrgencyLevel.HIGH,
    status: RequestStatus.IN_PROGRESS,
    aiSummary: "User is seeking performance optimization for a data cleaning script using pandas.",
    userId: "mock-user-2",
    user: {
      id: "mock-user-2",
      clerkId: "mock_clerk_2",
      email: "bob@example.com",
      name: "Bob Martinez",
      role: "CAN_HELP" as any,
      skills: ["Python", "Data Science"],
      interests: ["Education", "Healthcare"],
      trustScore: 920,
      badges: [],
      createdAt: new Date("2026-07-10"),
      updatedAt: new Date("2026-07-10"),
    },
    helpOffers: [],
    helperId: "mock-user-1",
    createdAt: new Date("2026-07-15"),
    updatedAt: new Date("2026-07-15"),
  },
];
